image: node:18

stages:
  - build
  - test
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install

run_tests:
  stage: test
  needs:
    - install_dependencies
  script: echo "Skipping tests..."

deploy_to_aws:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  needs:
    - install_dependencies
    - run_tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  script:
    - 'echo "Deploying with access key: $AWS_ACCESS_KEY_ID"'
    - 'npm install -g serverless'
    - 'npm run deploy'
